### ISSUE TITLE
TODO: Related work for 4 factors

### ISSUE THREAD

**Issue by latifaabdullayeva** [latifaabdullayeva/AutonomousSystemThesis#11]
The relationship between:
- [x] vibration and personality traits
- [ ] screen colours and personality traits
- [x] light colours and personality traits
- [x] music genre and personality traits
