### ISSUE TITLE
TODO: Mascot-Tablet interaction

### ISSUE THREAD

**Issue by latifaabdullayeva** [latifaabdullayeva/AutonomousSystemThesis#13]
- [ ] Mascot comes close to Tablet, Tablet changes the background colour
- [ ] Mascot measure the distance to Tablet (beacon)
- [ ] Initialise Tablet (beacon) (we use beacon API)
       * use beacon Manager
       * UI where the user chooses a beacon tag
- [ ] Every couple seconds, we sen GET status request from server "Do I need to change colour? Y/N"
- [ ] If the distance = 45-120 and the device to whom the mascot reaches is Tablet, then change colour
